### ISSUE TITLE
General Questions

### ISSUE THREAD

**Issue by Rolstenhouse** [wuhugh/uf_rest#1]
Do you have the URL where you hosted it on heroku?
Do you have an outline on what the new calls are?
It looks like a great start, but I don't see any documentation

**Comment by wuhugh** [comment]
Hey, sorry. I pushed the changes pretty late at night and went straight to bed haha. I'll update the README to include the information.

**Comment by wuhugh** [comment]
Here's the updated README. 
https://github.com/wuhugh/uf_rest/blob/master/README.md
